name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build React App
        run: npm run build

      - name: Upload to FTP
        run: |
          lftp ${{ secrets.FTP_SERVER }} -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "
          mirror -R -e ./build ${{ secrets.PATH_TO_FOLDER }};
          quit
          "
