name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload to SFTP
        run: |
          $securePassword = ConvertTo-SecureString "${{ secrets.FTP_PASSWORD }}" -AsPlainText -Force
          $myCred = New-Object System.Management.Automation.PSCredential ("${{ secrets.FTP_USERNAME }}", $securePassword)
          $session = New-SFTPSession -Host "${{ secrets.FTP_SERVER }}" -Port 22 -Credential $myCred
          Get-ChildItem -Path './dist' -File | ForEach-Object {
            Set-SFTPItem -SessionId $session.SessionId -Destination '/home/roqu0377/srapsproject2com' -Path $_.FullName -Force
          }
        shell: pwsh
